winget install Adobe.Acrobat.Reader.64-bit
winget install BurntSushi.ripgrep.MSVC
winget install Casey.Just
winget install Ditto.Ditto
winget install Git.Git
winget install GitHub.cli
winget install JRSoftware.InnoSetup
winget install Microsoft.Powershells
winget install Microsoft.VisualStudioCode
winget install Notepad++.Notepad++
winget install RProject.R
winget install Rustlang.Rustup
winget install astral-sh.uv
winget install chmln.sd
winget install direnv
winget install jftuga.less
winget install jj-vcs.jj
winget install junegunn.fzf
winget install starship
winget install zoxide
