winget install -e --id Adobe.Acrobat.Reader.64-bit
winget install -e --id Asana.Asana
winget install -e --id BurntSushi.ripgrep.MSVC
winget install -e --id Casey.Just
winget install -e --id Ditto.Ditto
winget install -e --id Git.Git
winget install -e --id GitHub.cli
winget install -e --id JRSoftware.InnoSetup
winget install -e --id Microsoft.VisualStudioCode
winget install -e --id Notepad++.Notepad++
winget install -e --id Obsidian.Obsidian
winget install -e --id RProject.R
winget install -e --id Rustlang.Rustup
winget install -e --id SumatraPDF.SumatraPDF
winget install -e --id abdenasser.NeoHtop
winget install -e --id astral-sh.uv
winget install -e --id chmln.sd
winget install -e --id dandavison.delta
winget install -e --id direnv
winget install -e --id jftuga.less
winget install -e --id jj-vcs.jj
winget install -e --id junegunn.fzf
winget install -e --id starship
winget install -e --id zoxide
